-- RenameTable
-- Hand-written (not autogenerated): Prisma's migration diff engine does not detect
-- model renames and would emit DROP TABLE "Account" + CREATE TABLE "ChartOfAccount",
-- which would destroy existing seeded rows. This migration performs an in-place
-- rename instead, preserving data and row identity.
ALTER TABLE "Account" RENAME TO "ChartOfAccount";

-- RenamePrimaryKey
ALTER TABLE "ChartOfAccount" RENAME CONSTRAINT "Account_pkey" TO "ChartOfAccount_pkey";

-- RenameForeignKey
ALTER TABLE "ChartOfAccount" RENAME CONSTRAINT "Account_parentId_fkey" TO "ChartOfAccount_parentId_fkey";
ALTER TABLE "ChartOfAccount" RENAME CONSTRAINT "Account_createdById_fkey" TO "ChartOfAccount_createdById_fkey";

-- RenameIndex
ALTER INDEX "Account_code_key" RENAME TO "ChartOfAccount_code_key";
ALTER INDEX "Account_branchId_type_idx" RENAME TO "ChartOfAccount_branchId_type_idx";
ALTER INDEX "Account_parentId_idx" RENAME TO "ChartOfAccount_parentId_idx";
